services:
  postgres:
    image: postgres
    container_name: mypostgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pastpursuit
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    volumes:
      - ./PastPursuitData/src/main/resources/migrations.sql:/docker-entrypoint-initdb.d/migrations.sql

  app:
    build: .
    container_name: myapp
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "jdbc:postgresql://mypostgres:5432/pastpursuit"
    networks:
      - mynetwork
    ports:
      - "8080:8080"
      - "8081:8081"

networks:
  mynetwork:
    driver: bridge