services:
  postgres:
    image: postgres
    container_name: mypostgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pastpursuit
    ports:
      - "5432:5432"
    volumes:
      - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql